# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
postbuy = Unit.create(name: '中国邮政集团公司上海市邮政国际邮购公司', desc: '上海邮政国际邮购公司', no: 'postbuy', short_name: 'postbuy', unit_type: 'postbuy')

delivery = Unit.create(name: '中国邮政集团公司上海市公司寄递事业部', desc: '上海市邮政寄递事业部', no: 'delivery', short_name: 'delivery', unit_type: 'delivery')

superadmin = User.create(username: 'superadmin', password: 'pwd12345', name: 'superadmin', role: 'superadmin', unit_id: 0)

unitadmin = User.create(username: 'admin', password: 'admin12345', name: '管理员', role: 'unitadmin', unit_id: 0)

# role_1 = Role.create(user: superadmin, unit: unit1, role: 'superadmin')

unit1 = Unit.create(name: '中国邮政集团公司上海市浦东新区寄递事业部', desc: '寄递事业部', no: '20120000000001', short_name: 'pdjd', unit_type: 'branch')
unit2 = Unit.create(name: '中国邮政集团公司上海市黄浦区寄递事业部', desc: '寄递事业部', no: '20190000000001', short_name: 'hpjd', unit_type: 'branch')
unit3 = Unit.create(name: '中国邮政集团公司上海市徐汇区寄递事业部', desc: '寄递事业部', no: '20190000000002', short_name: 'xhjd', unit_type: 'branch')
unit4 = Unit.create(name: '中国邮政集团公司上海市长宁区寄递事业部', desc: '寄递事业部', no: '20140000000012', short_name: 'cnjd', unit_type: 'branch')
unit5 = Unit.create(name: '中国邮政集团公司上海市普陀区寄递事业部', desc: '寄递事业部', no: '20140000000050', short_name: 'ptjd', unit_type: 'branch')
unit6 = Unit.create(name: '中国邮政集团公司上海市静安区寄递事业部', desc: '寄递事业部', no: '20190000000003', short_name: 'jajd', unit_type: 'branch')
unit7 = Unit.create(name: '中国邮政集团公司上海市虹口区寄递事业部', desc: '寄递事业部', no: '20190000000004', short_name: 'hkjd', unit_type: 'branch')
unit8 = Unit.create(name: '中国邮政集团公司上海市杨浦区寄递事业部', desc: '寄递事业部', no: '20140000000063', short_name: 'ypjd', unit_type: 'branch')
unit9 = Unit.create(name: '中国邮政集团公司上海市宝山区寄递事业部', desc: '寄递事业部', no: '20120000000011', short_name: 'bsjd', unit_type: 'branch')
unit10 = Unit.create(name: '中国邮政集团公司上海市闵行区寄递事业部', desc: '寄递事业部', no: '20120000000010', short_name: 'mhjd', unit_type: 'branch')
unit11 = Unit.create(name: '中国邮政集团公司上海市嘉定区寄递事业部', desc: '寄递事业部', no: '20120000000004', short_name: 'jdjd', unit_type: 'branch')
unit12 = Unit.create(name: '中国邮政集团公司上海市金山区寄递事业部', desc: '寄递事业部', no: '20120000000012', short_name: 'jsjd', unit_type: 'branch')
unit13 = Unit.create(name: '中国邮政集团公司上海市松江区寄递事业部', desc: '寄递事业部', no: '20120000000009', short_name: 'sjjd', unit_type: 'branch')
unit14 = Unit.create(name: '中国邮政集团公司上海市青浦区寄递事业部', desc: '寄递事业部', no: '20120000000015', short_name: 'qpjd', unit_type: 'branch')
unit15 = Unit.create(name: '中国邮政集团公司上海市奉贤区寄递事业部', desc: '寄递事业部', no: '20120000000014', short_name: 'fxjd', unit_type: 'branch')
unit16 = Unit.create(name: '中国邮政集团公司上海市崇明区寄递事业部', desc: '寄递事业部', no: '20120000000016', short_name: 'cmjd', unit_type: 'branch')
unit17 = Unit.create(name: '中国邮政集团公司上海市寄递事业部商企业务分公司', desc: '业务分公司', no: '20140000000070', short_name: 'sqfgs', unit_type: 'branch')
unit18 = Unit.create(name: '中国邮政集团公司上海市寄递事业部物流业务分公司', desc: '业务分公司', no: '20140000000074', short_name: 'wlfgs', unit_type: 'branch')
unit19 = Unit.create(name: '中国邮政集团公司上海市寄递事业部国际业务分公司', desc: '业务分公司', no: '20140000000073', short_name: 'gjfgs', unit_type: 'branch')
unit20 = Unit.create(name: '中国邮政集团公司上海市寄递事业部同城业务分公司', desc: '业务分公司', no: '20160000000001', short_name: 'tcfgs', unit_type: 'branch')


user1 = User.create(username: 'pinanqi', password: 'pinanqi12345', name: '皮楠淇', role: 'user', unit: unit1)
user2 = User.create(username: 'chenxuanrong', password: 'chenxuanrong12345', name: '陈宣融', role: 'user', unit: unit2)
user3 = User.create(username: 'pengjingqin', password: 'pengjingqin12345', name: '彭静琴', role: 'user', unit: unit2)
user4 = User.create(username: 'huangdong', password: 'huangdong12345', name: '黄栋', role: 'user', unit: unit3)
user5 = User.create(username: 'zhangjing', password: 'zhangjing12345', name: '张菁', role: 'user', unit: unit4)
user6 = User.create(username: 'taojian', password: 'taojian12345', name: '陶建', role: 'user', unit: unit5)
user7 = User.create(username: 'liuyanan', password: 'liuyanan12345', name: '刘亚男', role: 'user', unit: unit6)
user8 = User.create(username: 'jinhuiling', password: 'jinhuiling12345', name: '金会凌', role: 'user', unit: unit7)
user9 = User.create(username: 'shenxiang', password: 'shenxiang12345', name: '沈翔', role: 'user', unit: unit8)
user10 = User.create(username: 'shuiqin', password: 'shuiqin12345', name: '水琴', role: 'user', unit: unit8)
user11 = User.create(username: 'lushubei', password: 'lushubei12345', name: '陆姝琲', role: 'user', unit: unit9)
user12 = User.create(username: 'dingzhouyi', password: 'dingzhouyi12345', name: '丁舟怡', role: 'user', unit: unit9)
user13 = User.create(username: 'zhufan', password: 'zhufan12345', name: '朱樊', role: 'user', unit: unit10)
user14 = User.create(username: 'xuzheyi', password: 'xuzheyi12345', name: '徐哲毅', role: 'user', unit: unit10)
user15 = User.create(username: 'liangxiaoxi', password: 'liangxiaoxi12345', name: '梁小希', role: 'user', unit: unit11)
user16 = User.create(username: 'caixuanfeng', password: 'caixuanfeng12345', name: '蔡旋风', role: 'user', unit: unit12)
user17 = User.create(username: 'luyan', password: 'luyan12345', name: '陆燕', role: 'user', unit: unit12)
user18 = User.create(username: 'zhangliping', password: 'zhangliping12345', name: '张丽萍', role: 'user', unit: unit13)
user19 = User.create(username: 'caolan', password: 'caolan12345', name: '曹岚', role: 'user', unit: unit14)
user20 = User.create(username: 'ruanqiyu', password: 'ruanqiyu12345', name: '阮奇羽', role: 'user', unit: unit15)
user21 = User.create(username: 'pengyanhua', password: 'pengyanhua12345', name: '彭燕花', role: 'user', unit: unit15)
user22 = User.create(username: 'yuanjaijia', password: 'yuanjaijia12345', name: '袁佳佳', role: 'user', unit: unit16)
user23 = User.create(username: 'wuxiaoyu', password: 'wuxiaoyu12345', name: '吴晓珏', role: 'user', unit: unit17)
user24 = User.create(username: 'zhaoshuyan', password: 'zhaoshuyan12345', name: '赵书颜', role: 'user', unit: unit17)
user25 = User.create(username: 'liuhongling', password: 'liuhongling12345', name: '刘洪伶', role: 'user', unit: unit18)
user26 = User.create(username: 'tangjiayao', password: 'tangjiayao12345', name: '唐佳尧', role: 'user', unit: unit18)
user27 = User.create(username: 'caoyuqi', password: 'caoyuqi12345', name: '曹宇琦', role: 'user', unit: unit19)
user28 = User.create(username: 'chenlili', password: 'chenlili12345', name: '陈丽莉', role: 'user', unit: unit20)

user29 = User.create(username: 'pengwei', password: 'shyz1234', name: '彭微', role: 'user', unit: postbuy)
user30 = User.create(username: 'jinluming', password: 'shyz1234', name: '金路明', role: 'user', unit: postbuy)
user31 = User.create(username: 'zhangshaozhi', password: 'shyz1234', name: '张绍志', role: 'user', unit: postbuy)
user32 = User.create(username: 'xieshanshan', password: 'shyz1234', name: '谢姗姗', role: 'user', unit: postbuy)
user33 = User.create(username: 'yangyongmin', password: 'shyz1234', name: '杨永旻', role: 'user', unit: postbuy)
user34 = User.create(username: 'wangyan', password: 'shyz1234', name: '汪嫣', role: 'user', unit: postbuy)
user35 = User.create(username: 'xujun', password: 'shyz1234', name: '徐军', role: 'user', unit: postbuy)
user36 = User.create(username: 'zhouyijun', password: 'shyz1234', name: '周懿俊', role: 'user', unit: postbuy)
user37 = User.create(username: 'yinliang', password: 'shyz1234', name: '尹亮', role: 'user', unit: postbuy)
user38 = User.create(username: 'liujun', password: 'shyz1234', name: '刘军', role: 'user', unit: postbuy)
user39 = User.create(username: 'liubin', password: 'shyz1234', name: '刘斌', role: 'user', unit: postbuy)
user40 = User.create(username: 'panjiafeng', password: 'shyz1234', name: '潘加丰', role: 'user', unit: postbuy)
user41 = User.create(username: 'cuijia', password: 'shyz1234', name: '崔佳', role: 'user', unit: postbuy)
user42 = User.create(username: 'daijun', password: 'shyz1234', name: '戴骏', role: 'user', unit: postbuy)

user43 = User.create(username: 'guanlichen', password: 'guanlichen12345', name: '陈丽莉', role: 'user', unit: unit20)
user44 = User.create(username: 'guanlishen', password: 'guanlishen12345', name: '沈伟锋', role: 'user', unit: unit20)